version: "3"

networks:
  perpus-laravel:
    driver: bridge

services:
  app:
    build:
      context: .
    image: img-perpus-r00txtr1
    container_name: perpus-rootxtr1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: perpusku_gc
      DB_USERNAME: root
      DB_PASSWORD: 12345
    networks:
      - perpus-laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'perpusku_gc'
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: ""
    networks:
      - perpus-laravel

